# Note: we had to switch to version 3, rather than 3.9... and we are not sure why
# version: '3'

# services:
#   web:
#     build: .
#     command: python /code/manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#     ports:
#       - 8000:8000
#     depends_on: 
#       - db
#   db:
#     image: postgres:11
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - "POSTGRES_HOST_AUTH_METHOD=trust"

# volumes:
#   postgres_data:

version: "3.7"

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    