# Generated by Django 3.1.5 on 2021-01-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='draft_order',
            field=models.TextField(default='Draft Order will be generated by the Series Organizer once all Events and Users have been added to the Series.'),
        ),
    ]
