# Generated by Django 3.1.5 on 2021-01-20 04:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210115_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='draft_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='pick',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='remainder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='round',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
