# Generated by Django 3.1.5 on 2021-01-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210120_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='draft_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='series',
            name='draft_generation_complete',
            field=models.BooleanField(default=False),
        ),
    ]
