# Generated by Django 3.1.5 on 2021-01-21 01:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210121_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='draft_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None), blank=True, size=None),
        ),
    ]
