# Generated by Django 3.1.5 on 2021-01-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210121_0137'),
        ('api', '0003_auto_20210119_1931'),
    ]

    operations = [
    ]
